apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 5731d595.porter.run
kind: ConfigMap
metadata:
  name: porter-agent-manager-config
  namespace: porter-agent-system

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: porter-agent-config
  namespace: porter-agent-system
data:
  REDIS_HOST: {{ printf "%s-master" .Values.redis.fullnameOverride }}
  PORTER_HOST: {{ .Values.agent.porterHost }}
  PORTER_PORT: "{{ .Values.agent.porterPort }}"
  PORTER_TOKEN: '{{ .Values.agent.porterToken }}'
  CLUSTER_ID: "{{ .Values.agent.clusterID }}"
  PROJECT_ID: "{{ .Values.agent.projectID }}"
    
